[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.18'

gas_reports = ['FixedInterestOnlyLoans']

[rpc_endpoints]
anvil = '127.0.0.1:8545'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config